site_name: 财经分析报告系统
site_description: 基于AI的财经分析报告生成系统
site_author: Financial Report System
site_url: https://qipeijun.github.io/Financial-report/
docs_dir: docs
use_directory_urls: true
exclude_docs: '**/rss_data/**

  **/news_content/**

  **/collected_data.json

  **/*.txt

  '
repo_name: qipeijun/Financial-report
repo_url: https://github.com/qipeijun/Financial-report
edit_uri: edit/main/docs/
theme:
  name: material
  language: zh
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: white
    accent: blue
    toggle:
      icon: material/brightness-7
      name: 切换到深色模式
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: black
    accent: blue
    toggle:
      icon: material/brightness-4
      name: 切换到浅色模式
  features:
  - navigation.tabs
  - navigation.top
  - search.highlight
  - search.suggest
  - content.code.copy
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono
extra_css:
- stylesheets/extra.css
plugins:
- search:
    lang: zh
markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- admonition
- pymdownx.details
- attr_list
- md_in_html
- toc:
    permalink: true
nav:
- 首页: index.md
- 分析报告:
  - 2025年10月:
    - '2025-10-12':
      - PM Gemini报告: archive/2025-10/2025-10-12/reports/📅 2025-10-12 财经分析报告_evening_gemini.md
      - PM DeepSeek报告: archive/2025-10/2025-10-12/reports/📅 2025-10-12 财经分析报告_evening_deepseek.md
    - '2025-10-11':
      - Gemini报告: archive/2025-10/2025-10-11/reports/📅 2025-10-11 财经分析报告_gemini.md
      - DeepSeek报告: archive/2025-10/2025-10-11/reports/📅 2025-10-11 财经分析报告_deepseek.md
    - '2025-10-10':
      - Gemini报告: archive/2025-10/2025-10-10/reports/📅 2025-10-10 财经分析报告_gemini.md
      - DeepSeek报告: archive/2025-10/2025-10-10/reports/📅 2025-10-10 财经分析报告_deepseek.md
    - '2025-10-09':
      - Gemini报告: archive/2025-10/2025-10-09/reports/📅 2025-10-09 财经分析报告_gemini.md
      - DeepSeek报告: archive/2025-10/2025-10-09/reports/📅 2025-10-09 财经分析报告_deepseek.md
    - '2025-10-08':
      - Gemini报告: archive/2025-10/2025-10-08/reports/📅 2025-10-08 财经分析报告_gemini.md
      - DeepSeek报告: archive/2025-10/2025-10-08/reports/📅 2025-10-08 财经分析报告_deepseek.md
    - '2025-10-07':
      - Gemini报告: archive/2025-10/2025-10-07/reports/📅 2025-10-07 财经分析报告_gemini.md
      - DeepSeek报告: archive/2025-10/2025-10-07/reports/📅 2025-10-07 财经分析报告_deepseek.md
    - '2025-10-06':
      - Gemini报告: archive/2025-10/2025-10-06/reports/📅 2025-10-06 财经分析报告_gemini.md
      - DeepSeek报告: archive/2025-10/2025-10-06/reports/📅 2025-10-06 财经分析报告_deepseek.md
    - '2025-10-05':
      - Gemini报告: archive/2025-10/2025-10-05/reports/📅 2025-10-05 财经分析报告_gemini.md
      - DeepSeek报告: archive/2025-10/2025-10-05/reports/📅 2025-10-05 财经分析报告_deepseek.md
    - '2025-10-04':
      - Gemini报告: archive/2025-10/2025-10-04/reports/📅 2025-10-04 财经分析报告_gemini.md
      - DeepSeek报告: archive/2025-10/2025-10-04/reports/📅 2025-10-04 财经分析报告_deepseek.md
    - '2025-10-03':
      - Gemini报告: archive/2025-10/2025-10-03/reports/📅 2025-10-03 财经分析报告_gemini.md
      - DeepSeek报告: archive/2025-10/2025-10-03/reports/📅 2025-10-03 财经分析报告_deepseek.md
    - '2025-10-02':
      - Gemini报告: archive/2025-10/2025-10-02/reports/📅 2025-10-02 财经分析报告_gemini.md
      - DeepSeek报告: archive/2025-10/2025-10-02/reports/📅 2025-10-02 财经分析报告_deepseek.md
  - 2025年09月:
    - '2025-09-30':
      - Gemini报告: archive/2025-09/2025-09-30/reports/📅 2025-09-30 财经分析报告_gemini.md
      - DeepSeek报告: archive/2025-09/2025-09-30/reports/📅 2025-09-30 财经分析报告_deepseek.md
    - '2025-09-29':
      - '2025-09-29': archive/2025-09/2025-09-29/reports/📅 2025-09-29 财经分析报告.md
    - '2025-09-28':
      - '2025-09-28': archive/2025-09/2025-09-28/reports/📅 2025-09-28 财经分析报告.md
      - 🔥 热门话题:
        - 热门话题1 AI: archive/2025-09/2025-09-28/analysis/热门话题1_AI.md
        - 热门话题2 美国经济: archive/2025-09/2025-09-28/analysis/热门话题2_美国经济.md
        - 热门话题3 新能源: archive/2025-09/2025-09-28/analysis/热门话题3_新能源.md
      - 💎 潜力话题:
        - 潜力话题1 地缘政治: archive/2025-09/2025-09-28/analysis/潜力话题1_地缘政治.md
        - 潜力话题2 中国数据: archive/2025-09/2025-09-28/analysis/潜力话题2_中国数据.md
        - 潜力话题3 房地产: archive/2025-09/2025-09-28/analysis/潜力话题3_房地产.md
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/qipeijun
copyright: Copyright &copy; 2025 财经分析报告系统
