# 可提交的示例配置，请复制为 config/config.yml 并填写真实值
#
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# 📋 配置命名规范说明
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#
# 本项目采用混合命名策略：
#   • 本地配置文件：小写 + 下划线 (例如: api_keys.gemini)
#   • 环境变量/GitHub Secrets：大写 + 下划线 (例如: GEMINI_API_KEY)
#
# 🔄 配置映射关系（程序会自动转换）：
#   配置文件 (小写)              ←→   环境变量 (大写)
#   ─────────────────────────────────────────────────
#   api_keys.gemini              ←→   GEMINI_API_KEY
#   api_keys.deepseek            ←→   DEEPSEEK_API_KEY
#   notify.email.username        ←→   EMAIL_USERNAME
#   notify.email.password        ←→   EMAIL_PASSWORD
#   notify.email.smtp_server     ←→   SMTP_SERVER
#   notify.email.smtp_port       ←→   SMTP_PORT
#   notify.email.to              ←→   EMAIL_TO
#
# 💡 优先级：环境变量 > 配置文件
#   • 本地开发：使用 config.yml（小写配置）
#   • GitHub Actions：使用 Secrets（大写环境变量）
#   • 两者可以共存，程序会自动选择正确的配置
#
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# AI API 密钥
api_keys:
  gemini: "REPLACE_WITH_YOUR_GEMINI_API_KEY"
  deepseek: "REPLACE_WITH_YOUR_DEEPSEEK_API_KEY"

# 通知配置
notify:
  # 邮件通知配置
  email:
    enabled: false                          # 是否启用邮件通知
    smtp_server: "smtp.gmail.com"          # SMTP服务器地址
    smtp_port: 587                         # SMTP端口
    username: "your-email@gmail.com"       # 发件邮箱账号
    password: "your-app-password"          # 邮箱授权密码（Gmail需要应用专用密码）
    from: "财经报告 <your-email@gmail.com>"  # 发件人显示（可选）
    
    # 收件人邮箱（支持三种格式）：
    # 方式1：单个收件人（字符串）
    to: "recipient@example.com"
    
    # 方式2：多个收件人（逗号分隔的字符串）
    # to: "user1@example.com, user2@example.com, user3@example.com"
    
    # 方式3：多个收件人（YAML列表，推荐）
    # to:
    #   - "user1@example.com"
    #   - "user2@example.com"
    #   - "user3@example.com"
  
  # Server酱推送（旧版，待移除）
  server_chan_keys:
    - "REPLACE_WITH_SCT_KEY_1"
    - "REPLACE_WITH_SCT_KEY_2"
  
  # 企业微信（待实现）
  wechat:
    enabled: false
    webhook: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=YOUR_KEY"
  
  # 钉钉（待实现）
  dingtalk:
    enabled: false
    webhook: "https://oapi.dingtalk.com/robot/send?access_token=YOUR_TOKEN"
  
  # Telegram（待实现）
  telegram:
    enabled: false
    bot_token: "YOUR_BOT_TOKEN"
    chat_id: "YOUR_CHAT_ID"


