# 新闻质量筛选配置文件 - 宽松过滤模式
# 用于配置质量评分、筛选阈值、关键词等参数
#
# 策略：只过滤明显的垃圾内容和重复文章，尽量保留更多新闻给AI判断
# 预期保留率：70-80%（vs 原来的40%）

# ============================================================================
# 基础筛选参数
# ============================================================================

# 质量阈值（0-10分，低于此分数的文章将被过滤）
# 降低到1.5（原来2.5），更宽松，减少误删
quality_threshold: 1.5

# 去重相似度阈值（0-1，标题相似度超过此值视为重复）
dedup_threshold: 0.85

# 是否启用智能去重
enable_dedup: true

# 最大文章数限制（0表示不限制，给AI全部留下的文章）
max_articles: 0


# ============================================================================
# 来源权重配置（简化版，只保留基本区分）
# ============================================================================

source_weights:
  # 官方数据源（最高权重: 3.5）
  国家统计局: 3.5
  美联储: 3.5
  SEC: 3.5
  央行: 3.5
  
  # 高质量财经媒体（权重: 3.0）
  华尔街见闻: 3.0
  FT中文网: 3.0
  路透社: 3.0
  Bloomberg: 3.0
  
  # 默认权重（大部分来源，避免歧视）
  default: 2.0


# ============================================================================
# 重要关键词配置（宽松模式：禁用，避免误判）
# ============================================================================
# 
# 原因：关键词匹配容易误判（如"AI"匹配到"DAILY"），交给AI判断更准确
# 如需启用，请在 scoring_weights 中设置 keyword_contribution > 0

important_keywords: {}


# ============================================================================
# 垃圾关键词（只保留明显的营销推广词）
# ============================================================================

spam_keywords:
  # 明显的营销推广
  - 点击购买
  - 限时优惠
  - 扫码关注
  - 立即下载
  - 加微信
  - QQ群
  - 招商加盟
  - 免费领取
  
  # 明显的诱导性内容
  - 包赚不赔
  - 躺赚
  - 致富秘籍
  - 日入万元


# ============================================================================
# 低质量标题模式（只保留最明显的标题党）
# ============================================================================

low_quality_patterns:
  - '[！!]{3,}'             # 过多感叹号（震惊！！！）
  - '震惊[！!]{1,}'         # 震惊党
  - '不看后悔'
  - '速看'


# ============================================================================
# 评分权重配置（宽松模式：简化评分，减少误判）
# ============================================================================

scoring_weights:
  # 来源权重的乘数（默认: 1.0）
  source_weight_multiplier: 1.0
  
  # 内容长度加分上限（降低到1.0，避免长水文获高分）
  content_length_max_score: 1.0
  
  # 关键词加分上限（保留但不使用）
  keyword_max_score: 3.0
  
  # 关键词单个贡献系数（设为0，禁用关键词加分功能）
  keyword_contribution: 0
  
  # 垃圾内容单个扣分（加大惩罚: 2.0）
  spam_penalty_per_keyword: 2.0
  
  # 垃圾内容扣分上限（默认: 3.0）
  spam_penalty_max: 3.0
  
  # 标题党单个扣分（加大惩罚: 2.0）
  title_penalty_per_pattern: 2.0
  
  # 标题党扣分上限（默认: 2.0）
  title_penalty_max: 2.0
  
  # 时效性加分权重（降低到0.5，避免过度依赖时效性）
  timeliness_weight: 0.5


# ============================================================================
# 内容长度评分规则（宽松模式：降低要求）
# ============================================================================

content_length_scoring:
  # 摘要长度阈值和对应加分（降低阈值）
  summary:
    - threshold: 100
      score: 0.3
    - threshold: 300
      score: 0.3
  
  # 正文长度阈值和对应加分（降低阈值）
  content:
    - threshold: 300
      score: 0.3
    - threshold: 1000
      score: 0.3


# ============================================================================
# 时效性评分规则（小时数 -> 加分）
# ============================================================================

timeliness_scoring:
  - hours: 1
    score: 1.0
  - hours: 3
    score: 0.7
  - hours: 6
    score: 0.5
  - hours: 12
    score: 0.3
  - hours: 24
    score: 0.1


# ============================================================================
# 高级选项
# ============================================================================

advanced:
  # 是否启用调试日志
  enable_debug_log: false
  
  # 是否显示Top文章列表
  show_top_articles: true
  
  # Top文章列表显示数量
  top_articles_count: 10
  
  # 去重时的优先级字段（按顺序）
  dedup_priority_keys:
    - content
    - summary
    - quality_score
  
  # 快速去重模式（基于首字符分组优化）
  use_fast_dedup: true

