# 新闻质量筛选配置文件
# 用于配置质量评分、筛选阈值、关键词等参数

# ============================================================================
# 基础筛选参数
# ============================================================================

# 质量阈值（0-10分，低于此分数的文章将被过滤）
quality_threshold: 2.5

# 去重相似度阈值（0-1，标题相似度超过此值视为重复）
dedup_threshold: 0.85

# 是否启用智能去重
enable_dedup: true

# 最大文章数限制（0表示不限制，由其他参数控制）
max_articles: 0


# ============================================================================
# 来源权重配置（分数越高质量越高）
# ============================================================================

source_weights:
  # 官方数据源（最高权重: 5.0）
  国家统计局: 5.0
  美联储: 5.0
  SEC: 5.0
  央行: 5.0
  
  # 高质量国际财经媒体（权重: 3.0-3.5）
  华尔街见闻: 3.5
  FT中文网: 3.5
  路透社: 3.5
  Bloomberg: 3.0
  WSJ: 3.0
  经济学人: 3.0
  
  # 主流财经媒体（权重: 2.5）
  BBC商业: 2.5
  CNBC: 2.5
  ZeroHedge: 2.5
  "ETF Trends": 2.5
  
  # 国内财经平台（权重: 1.8-2.0）
  东方财富: 2.0
  36氪: 2.0
  中新网财经: 2.0
  百度股市通: 1.8
  
  # 默认权重（未配置的来源）
  default: 1.0


# ============================================================================
# 重要关键词配置（权重: 关键词在文本中每出现一次的加分）
# ============================================================================

important_keywords:
  # 宏观经济（权重: 1.5-2.0）
  美联储: 2.0
  央行: 2.0
  加息: 2.0
  降息: 2.0
  GDP: 1.5
  CPI: 1.5
  PPI: 1.5
  失业率: 1.5
  通货膨胀: 1.5
  通胀: 1.5
  经济数据: 1.5
  
  # 货币政策（权重: 1.5-1.8）
  货币政策: 1.8
  财政政策: 1.8
  利率: 1.5
  量化宽松: 1.5
  QE: 1.5
  缩表: 1.5
  
  # 市场重大事件（权重: 1.5-2.0）
  财报: 1.8
  业绩: 1.5
  并购: 2.0
  IPO: 1.8
  破产: 2.0
  退市: 1.8
  重组: 1.5
  
  # 政策监管（权重: 1.5-2.0）
  政策: 1.5
  监管: 1.8
  制裁: 2.0
  关税: 2.0
  贸易战: 2.0
  反垄断: 1.8
  罚款: 1.5
  
  # 行业热点（权重: 1.3-1.5）
  人工智能: 1.5
  AI: 1.5
  芯片: 1.5
  半导体: 1.5
  新能源: 1.5
  电动车: 1.3
  光伏: 1.3
  
  # 金融市场（权重: 1.5-2.0）
  暴跌: 1.5
  暴涨: 1.5
  崩盘: 2.0
  熊市: 1.5
  牛市: 1.5
  避险: 1.5
  恐慌: 1.5


# ============================================================================
# 垃圾关键词（出现即扣分）
# ============================================================================

spam_keywords:
  # 营销推广
  - 点击购买
  - 限时优惠
  - 扫码关注
  - 立即下载
  - 广告
  - 推广
  - 赞助
  - 招商加盟
  - 免费领取
  - 独家优惠
  - 火爆抢购
  - 秒杀
  
  # 诱导性内容
  - 致富秘籍
  - 躺赚
  - 暴富
  - 日入
  - 包赚
  - 稳赚
  - 必涨
  - 翻倍


# ============================================================================
# 低质量标题模式（正则表达式）
# ============================================================================

low_quality_patterns:
  - '[！!？?]{3,}'          # 过多感叹号/问号
  - '震惊[！!]{1,}'         # 震惊党
  - '不得不看'
  - '太[可恐]怕了'
  - '\d+倍'                # 涨X倍
  - '必看'
  - '绝密'
  - '劲爆'


# ============================================================================
# 评分权重配置（用于调整各项评分的重要性）
# ============================================================================

scoring_weights:
  # 来源权重的乘数（默认: 1.0）
  source_weight_multiplier: 1.0
  
  # 内容长度加分上限（默认: 2.0）
  content_length_max_score: 2.0
  
  # 关键词加分上限（默认: 3.0）
  keyword_max_score: 3.0
  
  # 关键词单个贡献系数（默认: 0.3）
  keyword_contribution: 0.3
  
  # 垃圾内容单个扣分（默认: 0.5）
  spam_penalty_per_keyword: 0.5
  
  # 垃圾内容扣分上限（默认: 3.0）
  spam_penalty_max: 3.0
  
  # 标题党单个扣分（默认: 0.5）
  title_penalty_per_pattern: 0.5
  
  # 标题党扣分上限（默认: 2.0）
  title_penalty_max: 2.0
  
  # 时效性加分权重（默认: 1.0）
  timeliness_weight: 1.0


# ============================================================================
# 内容长度评分规则
# ============================================================================

content_length_scoring:
  # 摘要长度阈值和对应加分
  summary:
    - threshold: 200
      score: 0.5
    - threshold: 500
      score: 0.5
  
  # 正文长度阈值和对应加分
  content:
    - threshold: 500
      score: 0.5
    - threshold: 1500
      score: 0.5


# ============================================================================
# 时效性评分规则（小时数 -> 加分）
# ============================================================================

timeliness_scoring:
  - hours: 1
    score: 1.0
  - hours: 3
    score: 0.7
  - hours: 6
    score: 0.5
  - hours: 12
    score: 0.3
  - hours: 24
    score: 0.1


# ============================================================================
# 高级选项
# ============================================================================

advanced:
  # 是否启用调试日志
  enable_debug_log: false
  
  # 是否显示Top文章列表
  show_top_articles: true
  
  # Top文章列表显示数量
  top_articles_count: 10
  
  # 去重时的优先级字段（按顺序）
  dedup_priority_keys:
    - content
    - summary
    - quality_score
  
  # 快速去重模式（基于首字符分组优化）
  use_fast_dedup: true

