name: Deploy Docsify Site

on:
  push:
    branches:
      - master  # 修正分支名称
  workflow_dispatch:  # 允许手动触发

# 添加必要的权限
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # 1️⃣ Checkout 仓库
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ 配置 Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # 3️⃣ 构建 Docsify 网站
      - name: Build Docsify site
        run: |
          mkdir -p _site
          
          # 迁移旧目录到 archive 按月归档
          if [ -f "scripts/organize_reports.py" ]; then
            echo "🔄 迁移旧目录到 archive..."
            python3 scripts/organize_reports.py
          fi
          
          # 自动生成侧边栏目录
          echo "🔄 生成侧边栏目录..."
          python3 scripts/generate_sidebar.py
          
          # 复制核心文件
          echo "📁 复制核心文件..."
          cp index.html README.md _site/
          
          # 复制侧边栏和封面
          if [ -f "web/_sidebar.md" ]; then 
            cp web/_sidebar.md _site/
            echo "✅ 复制侧边栏"
          fi
          if [ -f "web/_coverpage.md" ]; then 
            cp web/_coverpage.md _site/
            echo "✅ 复制封面页"
          fi
          if [ -f "web/_404.md" ]; then 
            cp web/_404.md _site/
            echo "✅ 复制404页面"
          fi

          # 复制归档目录（新结构）
          if [ -d "archive" ]; then 
            cp -r archive _site/
            echo "✅ 复制归档目录"
          else
            echo "⚠️ 未找到 archive 目录"
          fi
          
          # 显示构建结果
          echo "📊 构建完成，文件统计："
          find _site -type f | wc -l | xargs echo "总文件数："
          echo "📁 目录结构："
          find _site -type d | head -10

      # 4️⃣ 上传构建产物
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      # 5️⃣ 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
